### ISSUE TITLE
Crash when selecting article

### ISSUE THREAD

**Issue by hontogit** [yanus171/Handy-News-Reader#198]
Updated the app today from F-Droid, pulled new articles, opend one for reading and app crashed instantly. Since I use the setting to start the app with last opened article it crashes every time now.

Article I tried reading: [heise online ZombieLoad](https://www.heise.de/newsticker/meldung/Neue-Sicherheitsluecken-in-Intel-Prozessoren-ZombieLoad-4421217.html) :wink: 

Related crash report:
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at android.graphics.Color.parseColor(Color.java:147)
	at ru.yanus171.feedexfork.fragment.EntryFragment.UpdateFooter(EntryFragment.java:866)
	at ru.yanus171.feedexfork.fragment.EntryFragment$EntryPagerAdapter.displayEntry(EntryFragment.java:1253)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:1075)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:110)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

-------------------
Version : 0.8.2
Version Code: 155
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: One
Android Version : 7.1.2
User : android-build
Total Internal memory : 27479240704
Available Internal memory : 8423026688
-------------------

```

**Comment by meelten** [comment]
Same issue here. I set custom colors before opening article, don't know if related.

**Comment by yanus171** [comment]
OK, I will try to fix it soon

**Comment by yanus171** [comment]
Try it https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.8.3

**Comment by hontogit** [comment]
Thank you, it's fixed for me.

And cool, backup worked great. Nothing lost. :+1:
