### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by paulle** [yanus171/Handy-News-Reader#199]
App crashes at start (v 0.8.2)

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at android.graphics.Color.parseColor(Color.java:1384)
	at ru.yanus171.feedexfork.fragment.EntryFragment.UpdateFooter(EntryFragment.java:866)
	at ru.yanus171.feedexfork.fragment.EntryFragment$EntryPagerAdapter.displayEntry(EntryFragment.java:1253)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:1075)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:110)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6748)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

-------------------
Version : 0.8.2
Version Code: 155
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: H8266
Android Version : 9
User : BuildUser
Total Internal memory : 50505924608
Available Internal memory : 44103118848

**Comment by yanus171** [comment]
Same as #198. Which is already solved
