### ISSUE TITLE
App Crashes on Article Open and Stays Broken

### ISSUE THREAD

**Issue by tropappar** [yanus171/Handy-News-Reader#398]
**Describe the bug**
Since a few days (or even weeks), the app always crashes as soon as I open an article. Afterwards, the app stays broken until I delete the app data from the Android settings.

**To Reproduce**
1. Add a news feed (e.g. https://www.sueddeutsche.de/news/rss)
2. Let articles load
3. Click on any article to open article view
4. Screen turns black

**Expected behavior**
Instead of the black screen I should see the article view.

**Smartphone**
 - Device: Fairphone 3
 - OS: Android 9
 - Browser: Firefox
 - Version: 0.11.5

**Stacktrace from crash.txt**
```
UNCAUGHT EXCEPTION
[...]
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-[...]==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
[...]
```

**Comment by yanus171** [comment]
You'd better show the hole /sdcard/feedex/crash.txt

**Comment by tropappar** [comment]
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:270)
	at android.webkit.WebView.getFactory(WebView.java:2424)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2419)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2484)
	at android.view.View.<init>(View.java:4807)
	at android.view.View.<init>(View.java:4948)
	at android.view.ViewGroup.<init>(ViewGroup.java:659)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:403)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at android.webkit.WebView.<init>(WebView.java:308)
	at ru.yanus171.feedexfork.view.EntryView.<init>(EntryView.java:254)
	at ru.yanus171.feedexfork.fragment.EntryFragment.CreateEntryView(EntryFragment.java:1479)
	at ru.yanus171.feedexfork.fragment.EntryFragment.access$2100(EntryFragment.java:121)
	at ru.yanus171.feedexfork.fragment.EntryFragment$EntryPagerAdapter.instantiateItem(EntryFragment.java:1380)
	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:23173)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23173)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2726)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1580)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1863)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7207)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1012)
	at android.view.Choreographer.doCallbacks(Choreographer.java:823)
	at android.view.Choreographer.doFrame(Choreographer.java:758)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:998)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:265)
	... 78 more
Caused by: Ss
	at org.chromium.base.library_loader.LibraryLoader.a(PG:31)
	at org.chromium.base.library_loader.LibraryLoader.a(PG:11)
	at org.chromium.android_webview.AwBrowserProcess.a(PG:16)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:95)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(PG:12)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForP.<init>(PG:1)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForP.create(PG:1)
	... 80 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-ijZfeZiEYUfcWd8IwSn8Aw==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1669)
	at org.chromium.base.library_loader.LibraryLoader.a(PG:23)
	... 86 more

-------------------
Version : 0.11.5
Version Code: 189
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: FP3
Android Version : 9
User : build
Total Internal memory : 51245645824
Available Internal memory : 46977105920
-------------------
```

**Comment by yanus171** [comment]
Text "..libwebviewchromium.so" is 32-bit instead of 64-bit" points to 
problems with webview component on your phone. Try to update webview.

**Comment by tropappar** [comment]
Ok, that solved the problem. Thanks!
