### ISSUE TITLE
Crashes when opening app

### ISSUE THREAD

**Issue by Craeckie** [yanus171/Handy-News-Reader#468]
**Describe the bug**
Since the last update to 0.13.1 the app always crashes whenever I open it. I installed it from F-Droid.

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: Unable to resume activity {ru.yanus171.feedexfork/ru.yanus171.feedexfork.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.drawerlayout.widget.DrawerLayout.findViewById(int)' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4025)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4057)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7100)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.drawerlayout.widget.DrawerLayout.findViewById(int)' on a null object reference
at ru.yanus171.feedexfork.activity.HomeActivity.onResume(HomeActivity.java:323)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
at android.app.Activity.performResume(Activity.java:7612)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4017)
... 11 more

-------------------
Version : 0.13.1
Version Code: 203
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-T510
Android Version : 9
User : dpi
Total Internal memory : 57657352192
Available Internal memory : 7154601984
-------------------
```

**Comment by yanus171** [comment]
https://github.com/yanus171/Handy-News-Reader/releases/tag/v0.13.2
