### ISSUE TITLE
Crash at feeds update

### ISSUE THREAD

**Issue by hontogit** [yanus171/Handy-News-Reader#531]
When I trigger update for all feeds, the app often crashes after some time, I believe during the pictures loading process.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:1589)
	at android.graphics.drawable.Icon.writeToParcel(Icon.java:744)
	at android.os.Parcel.writeParcelable(Parcel.java:1496)
	at android.os.Parcel.writeValue(Parcel.java:1402)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1415)
	at android.os.Bundle.writeToParcel(Bundle.java:1157)
	at android.os.Parcel.writeBundle(Parcel.java:764)
	at android.app.Notification.writeToParcelImpl(Notification.java:2016)
	at android.app.Notification.writeToParcel(Notification.java:1910)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:870)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
	at android.app.NotificationManager.notify(NotificationManager.java:291)
	at android.app.NotificationManager.notify(NotificationManager.java:275)
	at ru.yanus171.feedexfork.view.StatusText$FetcherObservable$1.run(StatusText.java:192)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

-------------------
Version : 0.13.5
Version Code: 207
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: One
Android Version : 7.1.2
User : android-build
Total Internal memory : 27479240704
Available Internal memory : 4961746944

**Comment by hontogit** [comment]
It seems still present. But this report is a bit different at the end.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:1589)
	at android.graphics.drawable.Icon.writeToParcel(Icon.java:744)
	at android.app.Notification.writeToParcelImpl(Notification.java:1972)
	at android.app.Notification.writeToParcel(Notification.java:1910)
	at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:4414)
	at android.app.Service.startForeground(Service.java:703)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:319)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

-------------------
Version : 0.14.2
Version Code: 208
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: One
Android Version : 7.1.2
User : android-build
Total Internal memory : 27479240704
Available Internal memory : 5361700864
