### ISSUE TITLE
Crash when mark as read

### ISSUE THREAD

**Issue by Dreamer-4pda** [yanus171/Handy-News-Reader#540]
When mark as read from article list
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:207)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.toggleReadState(EntriesCursorAdapter.java:688)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.access$500(EntriesCursorAdapter.java:123)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter$3.onTouch(EntriesCursorAdapter.java:311)
	at android.view.View.dispatchTouchEvent(View.java:13949)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4012)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:14212)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7688)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7657)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7618)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7813)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

-------------------
Version : 0.14.1
Version Code: 207
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Redmi Note 4
Android Version : 10
User : gianfranco
Total Internal memory : 56004337664
Available Internal memory : 12238487552
-------------------

```

**Comment by Dreamer-4pda** [comment]
Ok, no crashing with new version, but article not hide from list after mark as read. Only refreshing list helps.
![Screenshot_20200511-231817__](https://user-images.githubusercontent.com/4630430/81608162-7e58e800-93de-11ea-9285-43abeb13eba9.png)
