### ISSUE TITLE
Crash when loading feed

### ISSUE THREAD

**Issue by hmonteiro** [yanus171/Handy-News-Reader#569]
Since a recent(ish) update, I've been seeing a crash when attempting to load the Questionable Content web comic RSS: 
```
Error
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.StringBuilder.toString()' on a null object reference
	at ru.yanus171.feedexfork.parser.RssAtomParser.endElement(RssAtomParser.java:426)
	at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:160)
	at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:501)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:488)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
	at android.util.Xml.parse(Xml.java:71)
	at ru.yanus171.feedexfork.service.FetcherService.parseXml(FetcherService.java:1487)
	at ru.yanus171.feedexfork.service.FetcherService.ParseRSSAndAddEntries(FetcherService.java:1402)
	at ru.yanus171.feedexfork.service.FetcherService.refreshFeed(FetcherService.java:1189)
	at ru.yanus171.feedexfork.service.FetcherService.access$300(FetcherService.java:153)
	at ru.yanus171.feedexfork.service.FetcherService$4.run(FetcherService.java:390)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:531)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:520)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:375)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)```

**To Reproduce**
Steps to reproduce the behavior:
1. Add `https://www.questionablecontent.net/QCRSS.xml` to the feeds
2. Update feeds
3. See error

**Expected behavior**
The feed should update and the articles should load.

**Smartphone (please complete the following information):**
 - Device: Xperia z3c
 - OS: lineage 16.1-official
 - Version 0.14.2

**Comment by yanus171** [comment]
Thanks. I will see it


hmonteiro <notifications@github.com> 16 июня 2020 г. 9:22:18 написал:

**Comment by yanus171** [comment]
I can't reproduce it. Anyway try https://drive.google.com/file/d/1aRGCQ-O-NjibH3gAF33-F0APENMvlm-u/view?usp=drivesdk
