### ISSUE TITLE
Update 0.15.22 crashes

### ISSUE THREAD

**Issue by Sarmadkh** [yanus171/Handy-News-Reader#675]
Updated today. But as soon as I start the app, it crashes. Deleting the old app and fresh install also doesn't work. Don't know why but also unable to send error log.

**Comment by touwys** [comment]
@Sarmadkh

I also updated HNR to v15.22 on my tablet moments ago, and insofar as I have tested it, it works well. The adapted Edit Feed page orientation is especially welcome.

**Comment by yanus171** [comment]
Give me crash.txt file from feedex folder (see full path in GNR storage 
settings)

**Comment by Sarmadkh** [comment]
¬ítfUNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:663)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:344)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.app.Dialog.show(Dialog.java:329)
	at android.preference.PreferenceScreen.showDialog(PreferenceScreen.java:223)
	at android.preference.PreferenceScreen.onClick(PreferenceScreen.java:178)
	at android.preference.Preference.performClick(Preference.java:997)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1170)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3148)
	at android.widget.AbsListView$3.run(AbsListView.java:4063)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

-------------------
Version : 0.15.15
Version Code: 225
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Redmi 4X
Android Version : 7.1.2
User : builder
Total Internal memory : 25753878528
Available Internal memory : 11230965760
-------------------

**Comment by islam2hamy** [comment]
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NoSuchMethodError: No virtual method setMin(I)V in class Landroid/widget/ProgressBar; or its super classes (declaration of 'android.widget.ProgressBar' appears in /system/framework/framework.jar:classes2.dex)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.bindView(EntriesCursorAdapter.java:611)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.getView(EntriesCursorAdapter.java:183)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2387)
	at android.widget.ListView.makeAndAddView(ListView.java:1970)
	at android.widget.ListView.fillSpecific(ListView.java:1400)
	at android.widget.ListView.layoutChildren(ListView.java:1721)
	at android.widget.AbsListView.onLayout(AbsListView.java:2176)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1892)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

-------------------
Version : 0.15.22
Version Code: 231
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Redmi 4X
Android Version : 7.1.2
User : builder
Total Internal memory : 10364874752
Available Internal memory : 2573168640
-------------------

**Comment by wombatch** [comment]
I also have android  7.1.2  and it crashes for me too. The stack trace doesn't look quite the same as that above but I see no point in adding another one here. I don't really want to uninstall because I have items that I have starred to reference later and don't want to lose them.
Hopefully a fix can be easily found.

**Comment by Struppi** [comment]
Got the same problems. I can't start the App anymore it crashes before it shows anything (only the reload status sign apears).
I even though found the crash.txt (I search after a folder named "ru.yanus171.feedexfork") it looks like that:
`��zUNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NoSuchMethodError: No virtual method setMin(I)V in class Landroid/widget/ProgressBar; or its super classes (declaration of 'android.widget.ProgressBar' appears in /system/framework/framework.jar:classes2.dex)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.bindView(EntriesCursorAdapter.java:611)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.getView(EntriesCursorAdapzter.java:183)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
	at android.widget.AbsListView.obtainView(AbsListView.java:3171)
	at android.widget.ListView.makeAndAddView(ListView.java:2139)
	at android.widget.ListView.fillSpecific(ListView.java:1463)
	at android.widget.ListView.layoutChildren(ListView.java:1870)
	at android.widget.AbsListView.onLayout(AbsListView.java:2943)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	zat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layzout(ViewGroup.java:5935)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1892)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:19055)
	at android.view.VizewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)z
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494z)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935z)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrzameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrazmeLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:954)
	at android.view.View.layout(View.java:19055)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2431)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootIzmpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.AzctivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

-------------------
Version : 0.15.22
Version Code: 231
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-J510FN
Android Version : 7.1.1
User : dpi
Total Internal memory : 11866615808
Available Internal memory : w>1254862848
-------------------`

**Comment by ThomasLeigh** [comment]
The answer from @yanus171:

Try to open the app in article screen (for example by home screen shortcut if it exists), go to article list settings and set Text size max to 0
Unfortunately I can fix that bug only after return from vacation (few weeks)

**Comment by islam2hamy** [comment]
It is now work

**Comment by wombatch** [comment]
Sadly no good for me, I have no other way to get into the app (or none that I can find anyway). Is there a config file or similar somewhere that I can edit?

**Comment by islam2hamy** [comment]
Open it from share link

**Comment by wombatch** [comment]
> Open it from share link

Thanks, got it ☺

**Comment by yanus171** [comment]
Try https://drive.google.com/file/d/1Y9ka-VuyM-kJ4vDVmPW51Gz4lbICNlMH/view?usp=sharing
