### ISSUE TITLE
Some RSS via https does not supported

### ISSUE THREAD

**Issue by Jaloou** [yanus171/Handy-News-Reader#684]
Many RRS feeds provided via https connection using modern valid and trusted security certificates issued by popular Let's Encrypt or by Sectigo, are unsupported by Handy News Reader on OS Android 4.1.2 even if the certificates added to the device as trusted and web-sites secured by they can be opened by web browsers without problems.

1. Install Handy News Reader app on a smartphone with OS Android 4.1.2 (like still popular model Samsung Galaxy S2 with its official firmware).
2. Open Handy News Reader app and try to add there RSS feed from a web-site secured with certificate issued by popular Let's Encrypt or by Sectigo, for example: oled-info.com
3. See error
![Screenshot_2021-07-24-14-44-02](https://user-images.githubusercontent.com/87898844/126867409-ffe3cdf6-fa02-463c-8c94-f9f22b79198b.png)

**Expected behavior**
RRS feeds provided via https secured by trusted and valid security certificates, must be supported all.

**Smartphone:**
 - Device: Samsung Galaxy S2
 - OS: Android 4.1.2.

**Comment by yanus171** [comment]
But it works on Android 5+

**Comment by Jaloou** [comment]
But a minimum OS requirement for Handy News Reader app is Android 4.0.
Moreover, RSS providing web-sites secured with popular certificates from Let's Encrypt or from Sectigo, are accessible via web-browsers without problems on Android 4.1.2.

So, it is the issue of Handy News Reader app.
Please, fix it.

**Comment by Jaloou** [comment]
Please, implement it: https://developer.android.com/training/articles/security-gms-provider
to your app for fix the issue.

**Comment by yanus171** [comment]
How does it help to resolve the issue?

**Comment by Jaloou** [comment]
> How does it help to resolve the issue?

If in Handy News Reader app on Android 4.1.2 instead 'http' put 'https' before an address of web-site secured with a certificate issued by Let's Encrypt or by Sectigo (for example, put 'https://oled-info.com') then there is a specific error message indicated in RSS like in the attached screenshot.
![Screenshot_2021-09-18-02-59-53](https://user-images.githubusercontent.com/87898844/133870647-ca8baa24-b7d2-4016-ac92-ae142090229e.png)
The best way to fix it described here
https://ankushg.com/posts/tls-1.2-on-android/

Moreover, it is important that this patch prevents a possible future risk if the currently trusted security protocols TLS 1.2 and TLS 1.3 eventually will be denied as vulnerable or weak and will replaced by newly invented security protocols (may be by something like TLS 1.4 or so).

Users of Handy News Reader have NOT to have a Google account even. They just need only to upgrade Google Play Services app and nothing more. It is easy possible and without Google Play store using third party apk web-sites like famous trusted Apkmirror and etc. Newly versions of Google Play Services app are provided regularly for the old Android 4.1.2.

I can be a free beta tester of the patch.

**Comment by yanus171** [comment]
@Jalloi, try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-922365500

But I had to add Googple play services dependency and apk size has increased by 1.5 MB

**Comment by Jaloou** [comment]
The issue was almost fixed! Thank you! ;-)
Many texts and images secured with certificates issued by Let's Encrypt or by Sectigo are loading and viewable.
![Screenshot_2021-09-19-01-57-35](https://user-images.githubusercontent.com/87898844/133913808-2531d7b6-cae5-458d-9cc0-9a5f399a2bee.png)
![Screenshot_2021-09-19-01-59-05](https://user-images.githubusercontent.com/87898844/133913817-bf9aee80-3f9d-42ac-8dab-dafe8b933bc6.png)

The small remained problem related to the issue is that only if RSS secured with a certificate issued by Let's Encrypt or by Sectigo then the user must manually add 'https' before the address while it is not necessly with other web-sites including and with encrypted by another certificates.

Unfortunately, I should mention here about a main biggest problem (not related to this issue): the app crashes often yet since reliase of its version 0.16.7 , which makes it almost unusable. I can provide the crash reports if you will ask.

The latest more or less stable version of the app was 0.15.12.
Please, if you can then implement this patch to the version 0.15.12. It will be more useful.

**Comment by yanus171** [comment]
You'd better give me a crash info

**Comment by Jaloou** [comment]
> You'd better give me a crash info

¬ízUNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.ExceptionInInitializerError
	at ru.yanus171.feedexfork.activity.HomeActivity.onCreateLoader(HomeActivity.java:521)
	at android.app.LoaderManagerImpl.createLoader(LoaderManager.java:544)
	at android.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:553)
	at android.app.LoaderManagerImpl.initLoader(LoaderManager.java:607)
	at ru.yanus171.feedexfork.activity.HomeActivity.onCreate(HomeActivity.java:213)
	at android.app.Activity.performCrzeate(Activity.java:5206)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
	at android.app.ActivityThread.access$700(ActivityThread.java:140)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at androizd.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteException: table label already exists (code 1): , while compiling: CREATE TABLE label (_id INTEGER PRIMARY KEzY AUTOINCREMENT, name TEXT, color TEXT, order_ INT);
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1013)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:624)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SzQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1663)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1594)
	at ru.yanus171.feedexfork.provider.DatabaseHelper.onUpgrade(DatabaseHelper.java:196)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:257)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.quezry(FeedDataContentProvider.java:417)
	at android.content.ContentProvider.query(ContentProvider.java:652)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:103)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:189)
	at android.content.ContentResolver.query(ContentResolver.java:372)
	at android.content.ContentResolver.query(ContentResolver.java:315)
	at ru.yanus171.feedexfork.service.FetcherService.GetExtrenalLinkFeedID(FetcherService.java:1zü099)
	at ru.yanus171.feedexfork.provider.FeedData.<clinit>(FeedData.java:100)
	... 19 more

-------------------
Version : 0.16.9
Version Code: 241
Package : ru.yanus171.feedexfork
FilePath : /data/data/ru.yanus171.feedexfork/files
Phone Model: GT-I9100
Android Version : 4.1.2
User : root
Total Internal memory : 6341312512
Available Internal memory : 614834176
-------------------

**Comment by yanus171** [comment]
@Jaloou see #713

**Comment by Jaloou** [comment]
The patch with its Google Play services dependency is not the cause of crashes. You can check it by applying the patch to the version 0.15.12, which was more or less stable.

> @Jaloou see #713

I did answered there.

I think the main persisting problem now is only that the app crashes. It needs to be solved for the first.
I do not know how I can help with it. May something which was changed after the version 0.15.12 triggers crashes. I think you should check the changees made right after the version 0.15.12.
