### ISSUE TITLE
handy news reader crash

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#686]
```

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Couldn't read row 650, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.GetPosByID(EntriesCursorAdapter.java:1150)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.RestoreListScrollPosition(EntriesListFragment.java:236)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.access$200(EntriesListFragment.java:115)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:212)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:174)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.15.22
Version Code: 231
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 6699413504
-------------------
```

**Comment by amit3s** [comment]
I have not seen this crash in the 0.16.7 update, thank you!
