### ISSUE TITLE
crash on null ptr

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#687]
```

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void ru.yanus171.feedexfork.view.EntryView.PageChange(int, ru.yanus171.feedexfork.view.StatusText)' on a null object reference
	at ru.yanus171.feedexfork.fragment.EntryFragment.PageDown(EntryFragment.java:428)
	at ru.yanus171.feedexfork.fragment.EntryFragment$7.onClick(EntryFragment.java:330)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.15.22
Version Code: 231
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 7712411648
------------------
```

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-919212176

**Comment by amit3s** [comment]
I have not seen this crash in the 0.16.7 update, thank you!
