### ISSUE TITLE
crash: NullPointerException: Can't toast on a thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#688]
```

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:157)
	at android.widget.Toast.getLooper(Toast.java:179)
	at android.widget.Toast.<init>(Toast.java:164)
	at android.widget.Toast.makeText(Toast.java:497)
	at android.widget.Toast.makeText(Toast.java:480)
	at android.widget.Toast.makeText(Toast.java:519)
	at ru.yanus171.feedexfork.utils.DebugApp.SendException(DebugApp.java:229)
	at ru.yanus171.feedexfork.utils.DebugApp$UncaughtExceptionHandler.uncaughtException(DebugApp.java:253)
	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-SystemWebView.apk-default-443008200:6)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
	at java.lang.Daemons$FinalizerWatchdogDaemon.finalizerTimedOut(Daemons.java:491)
	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:327)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)

-------------------
Version : 0.15.15
Version Code: 225
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 7446130688
-------------------
```

**Comment by yanus171** [comment]
Try list release
