### ISSUE TITLE
crash: NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.appcompat.widget.SearchView.findViewById(int)' on a null object reference

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#689]
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.appcompat.widget.SearchView.findViewById(int)' on a null object reference
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.onCreateOptionsMenu(EntriesListFragment.java:621)
	at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:2711)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManagerImpl.java:2711)
	at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:386)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:326)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.15.15
Version Code: 225
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 7496048640
-------------------
```

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-919212176

**Comment by amit3s** [comment]
I have not seen this crash in the 0.16.7 update, thank you!
