### ISSUE TITLE
Crashes in a loop on new update

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#692]
With the latest update from fdroid, I don't even get the list view or article view. No text gets displayed, and the app keeps crashing.

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalArgumentException: Illegal update. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/unread_entries/105768
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.update(FeedDataContentProvider.java:651)
	at android.content.ContentProvider.update(ContentProvider.java:1807)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
	at android.content.ContentResolver.update(ContentResolver.java:2356)
	at android.content.ContentResolver.update(ContentResolver.java:2318)
	at ru.yanus171.feedexfork.fragment.EntryFragment$1ReadAndOldWriter.run(EntryFragment.java:1144)
	at java.lang.Thread.run(Thread.java:923)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 6564810752
-------------------

```

**Comment by yanus171** [comment]
Post this to #683
