### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by danger-ahead** [yanus171/Handy-News-Reader#693]
The app fails to open. Have force stopped too. Nothing works. This is the error report:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.database.sqlite.SQLiteException: no such table: entrylabel (code 1 SQLITE_ERROR): , while compiling: SELECT entry_id, label_id FROM entrylabel
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:604)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:475)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:414)
	at android.content.ContentProvider.query(ContentProvider.java:1214)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:103)
	at android.content.ContentProvider.query(ContentProvider.java:1307)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
	at android.content.ContentResolver.query(ContentResolver.java:944)
	at android.content.ContentResolver.query(ContentResolver.java:880)
	at android.content.ContentResolver.query(ContentResolver.java:836)
	at ru.yanus171.feedexfork.utils.LabelVoc.init_(LabelVoc.kt:90)
	at ru.yanus171.feedexfork.utils.LabelVoc.access$init_(LabelVoc.kt:63)
	at ru.yanus171.feedexfork.utils.LabelVoc$initInThread$2.run(LabelVoc.kt:194)
	at java.lang.Thread.run(Thread.java:919)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Infinix X604
Android Version : 10
User : buildsrv-ci
Total Internal memory : 23733448704
Available Internal memory : 1459044352
-------------------
```

**Comment by yanus171** [comment]
try #683
