### ISSUE TITLE
Program crashes when I run the app

### ISSUE THREAD

**Issue by ygz213** [yanus171/Handy-News-Reader#695]
**Describe the bug**

Program is crashing when I run it and appearing share menu as "Sending critical error..."

**To Reproduce**

1. Run program

**Expected behavior**

App should run.

**Smartphone (please complete the following information):**

- Device: `TCL-8079`
- OS: `Android`
- Browser: Bromite
- Version `5.0.1`

**Additional context**
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.database.sqlite.SQLiteException: no such table: entrylabel (code 1): , while compiling: SELECT label_id, COUNT(entry_id) FROM ( SELECT * FROM entrylabel AS el LEFT JOIN ( SELECT _id, images_size, isread, images_size FROM entries WHERE (isread IS NULL OR isread=0)) AS e  ON (el.entry_id = e._id)  WHERE e._id IS NOT NULL) AS f1 GROUP BY label_id
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:898)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:509)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:405)
	at android.content.ContentProvider.query(ContentProvider.java:1003)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:103)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:221)
	at android.content.ContentResolver.query(ContentResolver.java:485)
	at android.content.ContentResolver.query(ContentResolver.java:429)
	at ru.yanus171.feedexfork.adapter.DrawerAdapter.SetLabelsNumber(DrawerAdapter.java:495)
	at ru.yanus171.feedexfork.adapter.DrawerAdapter.updateNumbers(DrawerAdapter.java:469)
	at ru.yanus171.feedexfork.adapter.DrawerAdapter.<init>(DrawerAdapter.java:112)
	at ru.yanus171.feedexfork.activity.HomeActivity.onLoadFinished(HomeActivity.java:532)
	at ru.yanus171.feedexfork.activity.HomeActivity.onLoadFinished(HomeActivity.java:104)
	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:488)
	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:456)
	at android.content.Loader.deliverResult(Loader.java:144)
	at android.content.CursorLoader.deliverResult(CursorLoader.java:109)
	at android.content.CursorLoader.deliverResult(CursorLoader.java:42)
	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5576)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/data/ru.yanus171.feedexfork/files
Phone Model: 8079
Android Version : 5.0.1
User : android
Total Internal memory : 4635631616
Available Internal memory : 465580032
-------------------
```

**Comment by yanus171** [comment]
See #683
