### ISSUE TITLE
Crash very frequent since 0.16.1

### ISSUE THREAD

**Issue by ochurlaud** [yanus171/Handy-News-Reader#696]
**Describe the bug**
I open a news and it crashes with this :

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalArgumentException: Illegal update. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/unread_entries/41437
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.update(FeedDataContentProvider.java:651)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:420)
	at android.content.ContentResolver.update(ContentResolver.java:1993)
	at ru.yanus171.feedexfork.fragment.EntryFragment$1ReadAndOldWriter.run(EntryFragment.java:1144)
	at java.lang.Thread.run(Thread.java:919)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-A310F
Android Version : 10
User : buildkite-agent
Total Internal memory : 12077481984
Available Internal memory : 2085482496
-------------------
```

**To Reproduce**
Open almost any news

**Expected behavior**
Do not crash.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: Samsung A3 2016
 - OS: Android 10 (LineageOS 17.1)
 - Browser???? ]
 - Version 0.16.1
 - 
**Additional context**
It worked perfect before the update and I cannot go revert the upgrade...

**Comment by yanus171** [comment]
See #683
