### ISSUE TITLE
Critical error with new version

### ISSUE THREAD

**Issue by Pada0** [yanus171/Handy-News-Reader#697]
**To Reproduce**
Start handy.
A message of error appear.

**message**
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalArgumentException: Illegal update. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/unread_entries/1062
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.update(FeedDataContentProvider.java:651)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:359)
	at android.content.ContentResolver.update(ContentResolver.java:1720)
	at ru.yanus171.feedexfork.fragment.EntryFragment$1ReadAndOldWriter.run(EntryFragment.java:1144)
	at java.lang.Thread.run(Thread.java:764)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: BV9900Pro
Android Version : 9
User : release
Total Internal memory : 120045522944
Available Internal memory : 8799817728
-------------------

**Comment by nin0-0** [comment]
I see the same after last upgrade:
```UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalArgumentException: Illegal update. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/unread_entries/185078
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.update(FeedDataContentProvider.java:651)
	at android.content.ContentProvider.update(ContentProvider.java:1807)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
	at android.content.ContentResolver.update(ContentResolver.java:2356)
	at android.content.ContentResolver.update(ContentResolver.java:2318)
	at ru.yanus171.feedexfork.fragment.EntryFragment$1ReadAndOldWriter.run(EntryFragment.java:1144)
	at java.lang.Thread.run(Thread.java:923)

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: POCO F1
Android Version : 11
User : buildkite-agent
Total Internal memory : 119384956928
Available Internal memory : 22405636096
-------------------

**Comment by kaimyel** [comment]
Same, except mine says Runtime Exception

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/feeds/8/unread_entries
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:409)
	at android.content.ContentProvider.query(ContentProvider.java:1379)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:103)
	at android.content.ContentProvider.query(ContentProvider.java:1475)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
	at android.content.ContentResolver.query(ContentResolver.java:1183)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at ru.yanus171.feedexfork.fragment.EntryFragment$15.doInBackground(EntryFragment.java:1028)
	at ru.yanus171.feedexfork.fragment.EntryFragment$15.doInBackground(EntryFragment.java:1005)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

-------------------
Version : 0.16.1
Version Code: 235
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Moto G (5S) Plus
Android Version : 11
User : arrow
Total Internal memory : 56881033216
Available Internal memory : 46643318784
-------------------

```

**Comment by yanus171** [comment]
It's the previous version. It should be 0.16.4 Try  
https://drive.google.com/file/d/1h7kA2AkpFi_XnxxqdEY-R--SxNkCeqHM/view?usp=sharing


kaimyel ***@***.***> 7 августа 2021 г. 7:02:19 написал:

**Comment by kaimyel** [comment]
Oh, i'm sorry. It was the recent Fdroid update (0.16.1) that crashed. But the apk from github couldn't be installed over it (signature issues, i assume).

So I uninstalled the fdroid update and did a fresh install of the github release, got my feeds from autobackup. Everything seems to be working fine again. Thanks.

**Comment by Pada0** [comment]
Thanks ! I will wait for the 0.16.4 version on f-drois

**Comment by nin0-0** [comment]
I didn't realise people installed through other channels than f-droid, I should've mentioned.

I'll wait for that update too, thanks so much for the work, I use the app daily !

**Comment by nin0-0** [comment]
I can confirm it working through f droid now
