### ISSUE TITLE
java.lang.IllegalStateException: Couldn't read row 638, col 0 from CursorWindow

### ISSUE THREAD

**Issue by amit3s** [yanus171/Handy-News-Reader#703]
With the 0.16.4 update, many of my previous crashes do not happen anymore - thanks! This is the one that happens the most now:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Couldn't read row 638, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.GetPosByID(EntriesCursorAdapter.java:1172)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.RestoreListScrollPosition(EntriesListFragment.java:257)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.access$200(EntriesListFragment.java:118)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:222)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:183)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
	at androidx.loader.content.CursorLoader.onStartLoading(CursorLoader.java:155)
	at androidx.loader.content.Loader.startLoading(Loader.java:285)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at ru.yanus171.feedexfork.activity.BaseActivity.onStart(BaseActivity.java:108)
	at ru.yanus171.feedexfork.activity.HomeActivity.onStart(HomeActivity.java:731)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.16.4
Version Code: 238
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: XT1097
Android Version : 11
User : buildkite-agent
Total Internal memory : 26186854400
Available Internal memory : 5254688768
-------------------

```

**Comment by amit3s** [comment]
I have not seen this crash in the 0.16.7 update, thank you!
