### ISSUE TITLE
"Label List" crash: Unable to find explicit activity class

### ISSUE THREAD

**Issue by Mrnofish** [yanus171/Handy-News-Reader#758]
**Describe the bug**

Tapping "Label List" in Advanced Features causes an exception.

**To Reproduce**
1. Open Drawer and tap on Settings
2. Tap on Advanced
3. Tap on Label List

**Expected behavior**
I've never used this feature and have no idea what is supposed to happen.

**Smartphone (please complete the following information):**
 - Device: GM1917
 - OS: LineageOS
 - Version 18.1 (Android 11)

**Additional context**

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.content.ActivityNotFoundException: Unable to find explicit activity class {ru.yanus171.feedexfork/ru.yanus171.feedexfork.activity.TagListActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2065)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
at android.app.Activity.startActivityForResult(Activity.java:5314)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
at android.app.Activity.startActivityForResult(Activity.java:5272)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
at android.app.Activity.startActivity(Activity.java:5658)
at android.app.Activity.startActivity(Activity.java:5611)
at android.preference.Preference.performClick(Preference.java:1181)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
at android.widget.AbsListView$3.run(AbsListView.java:4097)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.16.15
Version Code: 246
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: GM1917
Android Version : 11
User : buildkite-agent
Total Internal memory : 238665682944
Available Internal memory : 153128091648
-------------------
```

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079373727

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079762063
