### ISSUE TITLE
Regression, crash

### ISSUE THREAD

**Issue by xandro0777** [yanus171/Handy-News-Reader#761]
After latest update from F-droid I get following crash:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
 at ru.yanus171.feedexfork.parser.FeedFilters.removeText(FeedFilters.java:143)
 at ru.yanus171.feedexfork.view.EntryView.setHtml(EntryView.java:433)
 at ru.yanus171.feedexfork.fragment.EntryFragment$BaseEntryPagerAdapter.displayEntry(EntryFragment.java:1683)
 at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:1608)
 at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:153)
 at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
 at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
 at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
 at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
 at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
 at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
 at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
 at androidx.loader.content.Loader.deliverResult(Loader.java:132)
 at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
 at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
 at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
 at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
 at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
 at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:255)
 at android.app.ActivityThread.main(ActivityThread.java:8232)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

-------------------
Version : 0.16.21
Version Code: 251
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: RMX3085
Android Version : 11
User : root
Total Internal memory : 116188479488
Available Internal memory : 83119964160
-------------------
```
Happens when entering any article of this feed : https://blog.fefe.de/rss.xml

Once that happens the crash repeats any time I invoke the main activity of the app from the launcher which makes it pretty nasty. Only way to escape (besides clearing all data) is to invoke some other activity like add a feed.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079762063

**Comment by xandro0777** [comment]
>Try
>https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1079762063

Unfortunately I have the F-droid release installed so the signature is wrong. Also don't want to uninstall and reinstall because I have quite a few articles archived so that would be a big hassle.

**Comment by yanus171** [comment]
What about in app backup/restore?

**Comment by yanus171** [comment]
The backup file contains all feeds, groups, labels and started articles. The refresh after restore from backup show load remaining articles (in they are still in red channesl)

**Comment by yanus171** [comment]
You should check if you have a fresh backup file

**Comment by xandro0777** [comment]
Thanks, last update from F-Droid fixed this issue.

**Comment by yanus171** [comment]
The backup file contains all feeds, groups, labels and started articles. 
The refresh after restore from backup show load remaining articles (in they 
are still in red channesl)

**Comment by xandro0777** [comment]
Ok but after years of use some of the sites are defunct and ancient articles may have another url so some articles would be lost almost certainly.
