### ISSUE TITLE
App copies bug reports to clipboard

### ISSUE THREAD

**Issue by andelepeter** [yanus171/Handy-News-Reader#767]
The App copies lots of bug reports to the clipboard when in background. These are accidently inserted into other applications. The clipboard is not the right place for this. 

Example:

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:109)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3345)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6914)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1926)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1892)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:796)
	at ru.yanus171.feedexfork.service.FetcherService.StartService(FetcherService.java:1923)
	at ru.yanus171.feedexfork.service.AutoJobService.ExecuteDeleteOld(AutoJobService.java:232)
	at ru.yanus171.feedexfork.service.AutoJobService.onStartJob(AutoJobService.java:204)
	at android.app.job.JobService$1.onStartJob(JobService.java:62)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
	... 7 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:771)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:679)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:13987)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2943)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3030)

-------------------
Version : 0.16.21
Version Code: 251
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-A526B
Android Version : 12
User : dpi
Total Internal memory : 115075952640
Available Internal memory : 85159231488
-------------------

**Comment by yanus171** [comment]
The app copies  this info in clipboard on case when send dialog will not be 
shown. Due to the error.

**Comment by JStyle21** [comment]
I'm facing the same issue, this is very annoying
@yanus171 Why not add this as optional under advanced settings?

**Comment by yanus171** [comment]
Options were added in advanced settings to disable this

**Comment by JStyle21** [comment]
Thank you!
When is the next version that includes this?

**Comment by yanus171** [comment]
It's already in the last beta 
https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1484184430
