### ISSUE TITLE
android.app.ForegroundServiceStartNotAllowedException on Android 12

### ISSUE THREAD

**Issue by poggenpower** [yanus171/Handy-News-Reader#803]
HNR is throwing following exception regularly in the background. 
Not sure what exactly triggers this, but some internet research is pointing to issues with Android 12, which limits this functionality 

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:109)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service ru.yanus171.feedexfork/.service.FetcherService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3345)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6914)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1926)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1892)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:796)
	at ru.yanus171.feedexfork.service.FetcherService.StartService(FetcherService.java:1945)
	at ru.yanus171.feedexfork.service.AutoJobService.onStartJob(AutoJobService.java:224)
	at android.app.job.JobService$1.onStartJob(JobService.java:62)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
	... 7 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:771)
	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:679)
	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:14071)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2943)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3034)

-------------------
Version : 0.17.1
Version Code: 259
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-N970F
Android Version : 12
User : dpi
Total Internal memory : 246014783488
Available Internal memory : 177280565248
-------------------

**Comment by yanus171** [comment]
Disable battery optimization in app system settings

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1493296825
