### ISSUE TITLE
Error while importing lots of feeds

### ISSUE THREAD

**Issue by prirai** [yanus171/Handy-News-Reader#812]
**Describe the bug**
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
org.apache.harmony.xml.ExpatParser$ParseException: At line 310, column 8: not well-formed (invalid token)
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:528)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:487)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:324)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:287)
	at android.util.Xml.parse(Xml.java:109)
	at ru.yanus171.feedexfork.parser.OPML.importFromFile(OPML.java:210)
	at ru.yanus171.feedexfork.parser.OPML.importFromFile(OPML.java:193)
	at ru.yanus171.feedexfork.service.FetcherService.lambda$onHandleIntent$0$FetcherService(FetcherService.java:358)
	at ru.yanus171.feedexfork.service.-$$Lambda$FetcherService$uiX6YVMh8z8vVfTaE5Mfjxc8I3w.run(Unknown Source:4)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:631)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:620)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:352)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.17.7
Version Code: 265
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: moto g(60)
Android Version : 12
User : hudsongc
Total Internal memory : 115919532032
Available Internal memory : 62547349504
-------------------
```

**To Reproduce**
1. Import OPML feed with lots of (more than 100) feeds.
2. I'm unsure if its something specific to my OPML. Was exported from Feeder.

**Expected behavior**
Nothing much unexpected happens so I guess its not too much of a problem but it might be of help to you.

**Comment by yanus171** [comment]
Send me opml file
