### ISSUE TITLE
crash when click any article.

### ISSUE THREAD

**Issue by poggenpower** [yanus171/Handy-News-Reader#828]
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.View$OnClickListener.onClick(android.view.View)' on a null object reference
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter$1.onTouch(EntriesCursorAdapter.java:420)
	at android.view.View.dispatchTouchEvent(View.java:14306)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1873)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14569)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6024)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5827)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5318)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5493)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5550)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5375)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5349)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5322)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8095)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8046)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8006)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8218)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7715)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

-------------------
Version : 0.17.12
Version Code: 270
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: FP4
Android Version : 11
User : android-new
Total Internal memory : 238342561792
Available Internal memory : 212658356224
-------------------

Sometimes it is.working for.a while and then a click on any article causes a crash. Even after a force.stop the.first click could trigger a crash.

**Comment by yanus171** [comment]
Try the last beta #683

**Comment by poggenpower** [comment]
@yanus171 have installed via F-Droid I can't test you beta build. When will this Beta come into F-Droid?

**Comment by yanus171** [comment]
I hope in a week. You can temporary enable Articles text expanding setting 
in Article list section to prevent crashes. Or just don't tap on date and 
size text

**Comment by JohnVeness** [comment]
Is this same as #824?

**Comment by yanus171** [comment]
Yes, it is

**Comment by poggenpower** [comment]
For me taping on the date and the article picture has not triggered a 
crash, but taping the head line will trigger it in most cases but not 
every time.

On 2022-09-09 04:05, yanus171 wrote:

> I hope in a week. You can temporary enable Articles text expanding 
> setting
> in Article list section to prevent crashes. Or just don't tap on date 
> and
> size text
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/yanus171/Handy-News-Reader/issues/828#issuecomment-1241415577
[2]
