### ISSUE TITLE
crash when starting

### ISSUE THREAD

**Issue by poggenpower** [yanus171/Handy-News-Reader#834]
**Describe the bug**
App was working until it crashes immediatelyafter Start's no software update inbetween.

**To Reproduce**
1.It is enoughto open the app

**Expected behavior**
No crash

**Screenshots**
N/A

**Smartphone (please complete the following information)
See dump

**Additional context**
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup owner_package_name=ru.yanus171.feedexfork _display_name=HandyNewsReader_auto.backup mime_type=application/octet-stream _data=/storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup is_download=1 relative_path=Download/handy_news_reader/
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
	at android.content.ContentResolver.insert(ContentResolver.java:2152)
	at android.content.ContentResolver.insert(ContentResolver.java:2113)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:78)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:67)
	at ru.yanus171.feedexfork.service.FetcherService.lambda$onHandleIntent$0$FetcherService(FetcherService.java:323)
	at ru.yanus171.feedexfork.service.-$$Lambda$FetcherService$wjypVrONVXv_JftN8vWZn4kylEs.run(Unknown Source:2)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:611)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:600)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:319)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.17.14
Version Code: 272
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: FP4
Android Version : 11
User : android-new
Total Internal memory : 238342561792
Available Internal memory : 210126508032
-------------------

**Comment by yanus171** [comment]
Manually delete file storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup

**Comment by poggenpower** [comment]
Thank you, this did the trick, it is working again.

1 Oct 2022 08:00:27 yanus171 ***@***.***>:
