### ISSUE TITLE
Failed to create unique file at startup

### ISSUE THREAD

**Issue by floridop** [yanus171/Handy-News-Reader#835]
Hi

Usually the app would recover, but since this morning it crashes at every startup and I cannot use it anymore.

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup owner_package_name=ru.yanus171.feedexfork _display_name=HandyNewsReader_auto.backup mime_type=application/octet-stream _data=/storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup is_download=1 relative_path=Download/handy_news_reader/
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
	at android.content.ContentResolver.insert(ContentResolver.java:2152)
	at android.content.ContentResolver.insert(ContentResolver.java:2113)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:78)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:67)
	at ru.yanus171.feedexfork.service.FetcherService.lambda$onHandleIntent$0$FetcherService(FetcherService.java:323)
	at ru.yanus171.feedexfork.service.-$$Lambda$FetcherService$wjypVrONVXv_JftN8vWZn4kylEs.run(Unknown Source:2)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:611)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:600)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:319)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.17.14
Version Code: 272
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: FP3
Android Version : 11
User : jenkins
Total Internal memory : 51245486080
Available Internal memory : 8632758272
-------------------

```

**Comment by yanus171** [comment]
Same as #834

**Comment by yanus171** [comment]
try https://drive.google.com/file/d/172vLLMgZ9K3amHmqKaG66hy_rIiXDJJq/view?usp=sharing
