### ISSUE TITLE
App crashes when I open it

### ISSUE THREAD

**Issue by jreimone** [yanus171/Handy-News-Reader#837]
Steps to reproduce:
- open the app

Expected result:
I see the app and can access the unread articles.

Actual result:
I see the app only for a very short amount of time and then crashes. This is the error report my device provides me:

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup owner_package_name=ru.yanus171.feedexfork _display_name=HandyNewsReader_auto.backup mime_type=application/octet-stream _data=/storage/emulated/0/Download/handy_news_reader/HandyNewsReader_auto.backup is_download=1 relative_path=Download/handy_news_reader/
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
	at android.content.ContentResolver.insert(ContentResolver.java:2177)
	at android.content.ContentResolver.insert(ContentResolver.java:2138)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:78)
	at ru.yanus171.feedexfork.utils.FileUtils.copyFileToDownload(FileUtils.kt:67)
	at ru.yanus171.feedexfork.service.FetcherService.lambda$onHandleIntent$0$FetcherService(FetcherService.java:321)
	at ru.yanus171.feedexfork.service.-$$Lambda$FetcherService$wjypVrONVXv_JftN8vWZn4kylEs.run(Unknown Source:2)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:609)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:598)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:317)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.17.12
Version Code: 270
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Redmi Note 9 Pro
Android Version : 11
User : builder
Total Internal memory : 112419729408
Available Internal memory : 15958552576
-------------------

https://user-images.githubusercontent.com/1325591/198064755-9447fe50-d8ef-41fc-910e-59a0b1ef0302.mp4

Additional information:
It worked about a month ago.

**Comment by franconian** [comment]
Same behavior here. Identical report but version 0.17.14, version code 272, phone FP4, Android 11.
Till yesterday everything worked fine. Since today it's a mess. :-(

**Comment by yanus171** [comment]
Try the last release v0.17.21

**Comment by jreimone** [comment]
I updated via F-Droid to Version 0.17.14. The latest version is not provided there yet. Same error. Will try to install latest version manually

**Comment by jreimone** [comment]
Couldn't install it due to Google Play protection

**Comment by jreimone** [comment]
Seems that I need to wait until it's available in F-Droid

**Comment by jreimone** [comment]
@yanus171 when will the new version be in F-Droid?

**Comment by franconian** [comment]
Obviously depends on solving this issue: https://github.com/yanus171/Handy-News-Reader/issues/838

**Comment by jreimone** [comment]
New version solves this issue

**Comment by evolverine** [comment]
I'm on 0.17.22, and I still get this issue, every time I open the app.

**Comment by yanus171** [comment]
Try long tap on app shortcut and select Starred

**Comment by evolverine** [comment]
> Try long tap on app shortcut and select Starred

It gives me an error immediately. Same as Article Web Search and Last Read, though this last one gives me exception after exception, in a loop. I tried Unread, too, and it shows me a black screen that doesn't change, and slows down my phone until I manage to get out of it and close the app.
