### ISSUE TITLE
Crash Upon Open

### ISSUE THREAD

**Issue by Saijin-Naib** [yanus171/Handy-News-Reader#840]
**Describe the bug**
I can no longer open the app despite reboot and clean off cached data. 

**To Reproduce**
1. Go to app list 
2. Click on Handy News Reader
3. See error

**Expected behavior**
App will not crash at each launch 

**Smartphone (please complete the following information):**
 - Device: Teracube Teracube One TR1907Q 
 - OS: Android 10.1.0
 - Browser: Microsoft Edge
 - Version: 107.x

**Additional context**

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:443)
	at android.content.ContentProvider.query(ContentProvider.java:1214)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:108)
	at android.content.ContentProvider.query(ContentProvider.java:1307)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
	at android.content.ContentResolver.query(ContentResolver.java:944)
	at android.content.ContentResolver.query(ContentResolver.java:880)
	at android.content.ContentResolver.query(ContentResolver.java:836)
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1117)
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1075)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Teracube One
Android Version : 10
User : agentfabulous
Total Internal memory : 117760851968
Available Internal memory : 29210705920
-------------------
```

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1304538089

**Comment by Saijin-Naib** [comment]
Crash resolved by beta APK in #638.

Thank you so much!

**Comment by nin0-0** [comment]
seeing the same, even after reinstall
```
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done([AsyncTask.java:415](http://asynctask.java:415/))
	at java.util.concurrent.FutureTask.finishCompletion([FutureTask.java:383](http://futuretask.java:383/))
	at java.util.concurrent.FutureTask.setException([FutureTask.java:252](http://futuretask.java:252/))
	at [java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)([FutureTask.java:271](http://futuretask.java:271/))
	at android.os.AsyncTask$SerialExecutor$[1.run](http://1.run/)([AsyncTask.java:305](http://asynctask.java:305/))
	at java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1167](http://threadpoolexecutor.java:1167/))
	at java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:641](http://threadpoolexecutor.java:641/))
	at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:920](http://thread.java:920/))
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query([FeedDataContentProvider.java:443](http://feeddatacontentprovider.java:443/))
	at android.content.ContentProvider.query([ContentProvider.java:1408](http://contentprovider.java:1408/))
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query([FeedDataContentProvider.java:108](http://feeddatacontentprovider.java:108/))
	at android.content.ContentProvider.query([ContentProvider.java:1504](http://contentprovider.java:1504/))
	at android.content.ContentProvider$Transport.query([ContentProvider.java:272](http://contentprovider.java:272/))
	at android.content.ContentResolver.query([ContentResolver.java:1219](http://contentresolver.java:1219/))
	at android.content.ContentResolver.query([ContentResolver.java:1151](http://contentresolver.java:1151/))
	at android.content.ContentResolver.query([ContentResolver.java:1107](http://contentresolver.java:1107/))
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground([EntryFragment.java:1117](http://entryfragment.java:1117/))
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground([EntryFragment.java:1075](http://entryfragment.java:1075/))
	at android.os.AsyncTask$[3.call](http://3.call/)([AsyncTask.java:394](http://asynctask.java:394/))
	at [java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)([FutureTask.java:266](http://futuretask.java:266/))
	... 4 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: POCO F1
Android Version : 12
User : root
Total Internal memory : 118919880704
Available Internal memory : 1794732032
-------------------

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1304538089

**Comment by nin0-0** [comment]
Ah yes I had tried already, but something must have gone wrong in the download (it said "can't parse" when trying to install). 

I retried after your comment and it works (but I had to uninstall first). Thanks so much !!

**Comment by Saijin-Naib** [comment]
The current build seems to work well for me!
