### ISSUE TITLE
RuntimeException on startup

### ISSUE THREAD

**Issue by jakkdl** [yanus171/Handy-News-Reader#842]
**Describe the bug**
After maybe a week of using the app it now 100% crashes on startup. It can spawn notifications and did create an auto-backup, but anytime I try to open the app it crashes. Restarting phone did not help.

Uninstalling & reinstalling did help, I'll update if I get it to crash again.

**To Reproduce**
1. Launch app
2. Crash

**Expected behavior**
Not crash

**Smartphone (please complete the following information):**
 - Device: OnePlus A6003
 - OS: 19-20221115-NIGHTLY-enchilada
 - Browser: firefox
 - Version: 107.1.0
 - Installation source: F-Droid

**Additional context**
```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:443)
	at android.content.ContentProvider.query(ContentProvider.java:1408)
	at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:108)
	at android.content.ContentProvider.query(ContentProvider.java:1504)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:272)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1117)
	at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1075)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: ONEPLUS A6003
Android Version : 12
User : root
Total Internal memory : 115717931008
Available Internal memory : 46508548096
-------------------
```

**Comment by jakkdl** [comment]
oh, reinstalling helped for a second ... until it finished fetching my feeds I imported from backup. So might be one of the feeds causing it

**Comment by jakkdl** [comment]
Sorry for duplicate issue, but beta releases indeed solved my problem. Thanks! ❤️
