### ISSUE TITLE
Filtered articles to display filter keyword/s

### ISSUE THREAD

**Issue by DickinsonSa** [yanus171/Handy-News-Reader#846]
An proposed enhancement. 

Overview :

Currently, articles which are filtered (via global filter) are *starred with no indication of which filter applied. 

Articles which are given a label, show the label in the article list view (nice). 

Feature request :

Where an article has been filtered, to show the filter details (say where the current label tag shows) - alongside a label also. 

Also considered :

When an article matches a filter, create (unless one already exists) a new label named as the filter. This would give a nice collection of similar articles. This is a more elegant method. 

Exclusions :

Articles matched via a regular expression search might be difficult to display: so this may need to be limited to keywords only.

**Comment by yanus171** [comment]
So you mean: an ability to set a label in star filter type?


DickinsonSa ***@***.***> 23 января 2023 г. 16:38:32 написал:

**Comment by DickinsonSa** [comment]
Yes, I thought it might help identify which filter the article matches. 

It might not be the best solution, but if my articles are filtered (*starred) I currently don't know exactly why - other than they matched one of my global filters.

**Comment by DickinsonSa** [comment]
Hi, was just wondering if there is a proposed time scale (date) for this enhancement?

**Comment by yanus171** [comment]
The more you remind me about it  the quicker it will be implemented :)

**Comment by DickinsonSa** [comment]
Cool, great to hear. Should be very useful. Thank you.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1640780323

**Comment by DickinsonSa** [comment]
> Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1640780323

I tried and I see differences :-

Now I set each filter rule up with a label tag.
This label tag then appears in my LH menu area under 'labels'. 
Each time a filter rule is met, the article is given that label.

Is this how you have implemented it? Now I have this new version I can't remember how it used to work - sorry my memory is not great anymore.

Anyways, apart from having to set up the labels myself, it works great!

Have I understood this correctly?

Just two small issues : I can't change my label settings from 'title' to 'author' it just ignores the change.

When the labels tab in LH column is collapsed, there is no total. 

I can live with the above - maybe for future reference. 

Fantastic work - many thanks.

**Comment by yanus171** [comment]
Yes you understood it right. But why you say about setting labels manually. 
Did you mean some way to set it automatically?

I confirm the first problem. Thank you. I will fix it.

What is LH menu?

**Comment by DickinsonSa** [comment]
Sorry LH = Left Hand

**Comment by DickinsonSa** [comment]
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter labels
	at ru.yanus171.feedexfork.utils.LabelVoc.setEntry(Unknown Source:2)
	at ru.yanus171.feedexfork.service.FetcherService.lambda$Process$5(FetcherService.java:473)
	at ru.yanus171.feedexfork.service.FetcherService$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:623)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:611)
	at ru.yanus171.feedexfork.service.FetcherService.Process(FetcherService.java:451)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:327)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.18.23
Version Code: 305
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-T500
Android Version : 12
Board : bengal
Brand : samsung
Device : gta4lwifi
Model : SM-T500
Product : gta4lwifieea
User : dpi
Total Internal memory : 23506939904
Available Internal memory : 6123499520
-------------------

**Comment by DickinsonSa** [comment]
Hi, getting a few fails with this update.

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1646071539

**Comment by DickinsonSa** [comment]
Great - doesn't crash when I load up or do an individual rss feed refresh but, it crashes when I go to a feed filter...

See enclosed...


UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter s
	at ru.yanus171.feedexfork.utils.LabelVoc.stringToList(Unknown Source:2)
	at ru.yanus171.feedexfork.adapter.FiltersCursorAdapter.bindView(FiltersCursorAdapter.java:75)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:296)
	at android.widget.AbsListView.obtainView(AbsListView.java:2662)
	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1309)
	at android.widget.ListView.makeAndAddView(ListView.java:2174)
	at android.widget.ListView.fillDown(ListView.java:874)
	at android.widget.ListView.fillFromTop(ListView.java:943)
	at android.widget.ListView.layoutChildren(ListView.java:1898)
	at android.widget.AbsListView.onLayout(AbsListView.java:2448)
	at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

-------------------
Version : 0.18.24
Version Code: 306
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: EML-L09
Android Version : 10
Board : EML
Brand : HUAWEI
Device : HWEML
Model : EML-L09
Product : EML-L09
User : test
Total Internal memory : 119661395968
Available Internal memory : 94368075776
-------------------

Thanks for the hard work

**Comment by yanus171** [comment]
And https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1646442793

**Comment by DickinsonSa** [comment]
Hi, this is looking near perfect now - many thanks. There was just one minor hiccup in the navigation - but it's not causing any problems. I'll try to explain it - 

If you long click on a feed you go to 'edit a feed' and then you select 'filter' - which takes you to 'edit a rule'. 

When going from 'edit a rule' then click 'with labels' then in 'Filter by labels' click 'setup' you go to the label list where you can create and re-arrange the new label. This is all fine **but** when you click exit on phone (because that is the only way to go back) you are taken right back to the feed list. 

I would expect to go back to 'edit a rule'. 

This isn't a big deal because if you long click on the feed again you are taken back to 'edit the rule' where you left off. 

Hope that makes sense. 

Excellent work, I also like the fact that you can see all the labels in the 'Starred' section too. 

Thank you.

**Comment by DickinsonSa** [comment]
Hi, getting a crash on first load - here's the log.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashSet.isEmpty()' on a null object reference
	at ru.yanus171.feedexfork.service.FetcherService.lambda$Process$5(FetcherService.java:472)
	at ru.yanus171.feedexfork.service.FetcherService$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:623)
	at ru.yanus171.feedexfork.service.FetcherService.LongOper(FetcherService.java:611)
	at ru.yanus171.feedexfork.service.FetcherService.Process(FetcherService.java:451)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:327)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

-------------------
Version : 0.18.25
Version Code: 307
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-T500
Android Version : 12
Board : bengal
Brand : samsung
Device : gta4lwifi
Model : SM-T500
Product : gta4lwifieea
User : dpi
Total Internal memory : 23506939904
Available Internal memory : 5475344384
-------------------
