### ISSUE TITLE
App crash while updating rss-feeds

### ISSUE THREAD

**Issue by Rubylion** [yanus171/Handy-News-Reader#85]
Hi. Sadly the app crashes, while I update the news.Says out if memory, but can't be, as I hace enough storage(approx. 2GB) internal, and more than 20 GB external capacity.
I'm on a Samsung S7, with 16GB memory and on LineageOS 14.
Here's the crashlog
java.lang.OutOfMemoryError: Failed to allocate a 268501000 byte allocation with 16777216 free bytes and 76MB until OOM
	at java.util.Arrays.copyOf(Arrays.java:3352)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:417)
	at java.lang.StringBuilder.append(StringBuilder.java:133)
	at java.lang.StringBuilder.append(StringBuilder.java:180)
	at java.lang.StringBuilder.append(StringBuilder.java:176)
	at org.jsoup.nodes.Node.indent(Node.java:607)
	at org.jsoup.nodes.Element.outerHtmlHead(Element.java:1363)
	at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:709)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:45)
	at org.jsoup.nodes.Node.outerHtml(Node.java:573)
	at org.jsoup.nodes.Element.html(Element.java:1407)
	at org.jsoup.nodes.Element.html(Element.java:1401)
	at ru.yanus171.feedexfork.utils.ArticleTextExtractor.extractContent(ArticleTextExtractor.java:68)
	at ru.yanus171.feedexfork.service.FetcherService.mobilizeEntry(FetcherService.java:516)
	at ru.yanus171.feedexfork.service.FetcherService.mobilizeAllEntries(FetcherService.java:420)
	at ru.yanus171.feedexfork.service.FetcherService.onHandleIntent(FetcherService.java:328)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yanus171** [comment]
So you know the feed url with crash the app? We can set Content extract rule in settings for that feed to reduce the article output

**Comment by Rubylion** [comment]
Well, at the moment there aren't any problems. Maybe it was a parsing error for a certain article???
If there's anything going on, I will inform you. Good job, btw.

**Comment by Rubylion** [comment]
same problem again: Hi. I got the problem again. The app has fetched all articles and has used the mobilizer, then while updating ghe images, it crashes on a certain article. It's not possible to find out which one , but I thought, while it sometimes hapoens with some feeds, if there isn't a possibility, to skip the error causing one and process ahaid. Cause now the app can't update anything anymore, while it hangs on that particular feed.

**Comment by yanus171** [comment]
Does not it try to send a crash mail? If not, send me a file /storage/feedex/crash.txt

**Comment by Rubylion** [comment]
Hi. Got some problems again.
Here's the crash-log

java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at android.graphics.Color.parseColor(Color.java:147)
	at ru.yanus171.feedexfork.fragment.EntryFragment.UpdateFooter(EntryFragment.java:866)
	at ru.yanus171.feedexfork.fragment.EntryFragment$EntryPagerAdapter.displayEntry(EntryFragment.java:1253)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:1075)
	at ru.yanus171.feedexfork.fragment.EntryFragment.onLoadFinished(EntryFragment.java:110)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by yanus171** [comment]
See #201
