### ISSUE TITLE
"couldn't read from cursorwindow" 0.18.10 crash galore

### ISSUE THREAD

**Issue by Mrnofish** [yanus171/Handy-News-Reader#850]
0.18.10 is almost unusable for me, because of repeated crashes when switching back from article view to list.

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Couldn't read row 123, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
	at android.widget.CursorAdapter.getItemId(CursorAdapter.java:266)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.reinit(EntriesCursorAdapter.java:1348)
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.changeCursor(EntriesCursorAdapter.java:1283)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:238)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished(EntriesListFragment.java:203)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

-------------------
Version : 0.18.10
Version Code: 291
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: GM1917
Android Version : 11
User : root
Total Internal memory : 238665682944
Available Internal memory : 136399659008
-------------------
```

**Comment by yanus171** [comment]
Try
