### ISSUE TITLE
Widget not working, keeps crashing

### ISSUE THREAD

**Issue by Rubylion** [yanus171/Handy-News-Reader#86]
The widget complains about a missind permission, but I granted everything that's possible, wighout any luck

Phone: Samsung S7 :: LineafeOS 14

Crashlog:
java.lang.SecurityException: Permission Denial: reading ru.yanus171.feedexfork.provider.FeedDataContentProvider uri content://ru.yanus171.feedexfork.provider.FeedData/entries from pid=4542, uid=10236 requires the provider be exported, or grantUriPermission()
	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:610)
	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:485)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.content.ContentResolver.query(<Xposed>)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.content.ContentResolver.query(<Xposed>)
	at ru.yanus171.feedexfork.widget.WidgetFeedsFactory.computeCursor(WidgetService.java:155)
	at ru.yanus171.feedexfork.widget.WidgetFeedsFactory.onDataSetChanged(WidgetService.java:139)
	at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.onDataSetChanged(RemoteViewsService.java:142)
	at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:49)
	at android.os.Binder.execTransact(Binder.java:565)

**Comment by yanus171** [comment]
App widget are not working now. Google forced me to set strick permission on content provider that break the app widget functionality. I can make in work again (exported=true) in manifest. But such a version will be abadoned in Google Play.

**Comment by yanus171** [comment]
Do you really need app widget? Are the news are so urgent information, that needs to be displayed on the home screen?

**Comment by Rubylion** [comment]
Thanx for the answer. Well, I like to have a widget for news, but of course it's not life dependent😃. A widget is always a nice way to access the information that's somewhere stored in your phone.  Also many RSS reader have a widget, for that it could be a (+) when you offer it in GPlay.

**Comment by yanus171** [comment]
in version https://github.com/yanus171/Flym/releases/tag/v0.7.39 I have (temporary?) removed app wodgets. For it was causing app crash

**Comment by ThomasLeigh** [comment]
Will widgets come back some day?

**Comment by yanus171** [comment]
Why we need widgets?

**Comment by ThomasLeigh** [comment]
I suppose the same reason why any widgets are used by those who prefer them: because they like it or find it appealing or useful. Now I personally don't use widgets almost at all -  but there was a time when I did.

I'll tell You what would be a good idea for a _HNR_ widgets in My opinion: something which inform (via simple graphic sign) that there is or there are some important article(s) (marked as _starred_ by the global filter).

Besides, I much liked the widget which displayed a coffee cup with the number of _Unread_ articles - it was great to have it on the desktop - and at the time I've used it to launch the app.

**Comment by Ryuno-Ki** [comment]
> Besides, I much liked the widget which displayed a coffee cup with the number of Unread articles - it was great to have it on the desktop - and at the time I've used it to launch the app.

Same. But after a while it can get frustrating to watch the number increase (I have too many feeds in my list, I know :-b)

**Comment by yanus171** [comment]
> it can get frustrating to watch the number increase
Same. That's why I see no use in it

**Comment by ThomasLeigh** [comment]
But there are people who read less (or more) enough not to feel frustration, or not everybody feels it anyway. Besides, the widget could display an estimated time of reading instead of number of articles (it could be configurable in widget's settings - or there could be separate widgets).

I still like the idea.

**Comment by SIRSteiner** [comment]
Because there is no widget this issue isn't an issue anymore. If anyone needs a widget you should add a feature request.
