### ISSUE TITLE
crashing on article open and on app start

### ISSUE THREAD

**Issue by nin0-0** [yanus171/Handy-News-Reader#864]
**Describe the bug**
I installed grapheneos on google pixel 7 and I am seeing this new crash on this device/os.

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.IllegalStateException: Couldn't read row 203, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong([CursorWindow.java:539](http://cursorwindow.java:539/))
	at android.database.AbstractWindowedCursor.getLong([AbstractWindowedCursor.java:78](http://abstractwindowedcursor.java:78/))
	at android.database.CursorWrapper.getLong([CursorWrapper.java:131](http://cursorwrapper.java:131/))
	at android.widget.CursorAdapter.getItemId([CursorAdapter.java:266](http://cursoradapter.java:266/))
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.reinit([EntriesCursorAdapter.java:1348](http://entriescursoradapter.java:1348/))
	at ru.yanus171.feedexfork.adapter.EntriesCursorAdapter.changeCursor([EntriesCursorAdapter.java:1283](http://entriescursoradapter.java:1283/))
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished([EntriesListFragment.java:238](http://entrieslistfragment.java:238/))
	at ru.yanus171.feedexfork.fragment.EntriesListFragment$1.onLoadFinished([EntriesListFragment.java:203](http://entrieslistfragment.java:203/))
	at [androidx.loader.app](http://androidx.loader.app/).LoaderManagerImpl$LoaderObserver.onChanged([LoaderManagerImpl.java:250](http://loadermanagerimpl.java:250/))
	at androidx.lifecycle.LiveData.considerNotify([LiveData.java:133](http://livedata.java:133/))
	at androidx.lifecycle.LiveData.dispatchingValue([LiveData.java:151](http://livedata.java:151/))
	at androidx.lifecycle.LiveData.setValue([LiveData.java:309](http://livedata.java:309/))
	at androidx.lifecycle.MutableLiveData.setValue([MutableLiveData.java:50](http://mutablelivedata.java:50/))
	at [androidx.loader.app](http://androidx.loader.app/).LoaderManagerImpl$LoaderInfo.setValue([LoaderManagerImpl.java:189](http://loadermanagerimpl.java:189/))
	at [androidx.loader.app](http://androidx.loader.app/).LoaderManagerImpl$LoaderInfo.onLoadComplete([LoaderManagerImpl.java:174](http://loadermanagerimpl.java:174/))
	at androidx.loader.content.Loader.deliverResult([Loader.java:132](http://loader.java:132/))
	at androidx.loader.content.CursorLoader.deliverResult([CursorLoader.java:109](http://cursorloader.java:109/))
	at androidx.loader.content.CursorLoader.deliverResult([CursorLoader.java:41](http://cursorloader.java:41/))
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete([AsyncTaskLoader.java:258](http://asynctaskloader.java:258/))
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute([AsyncTaskLoader.java:83](http://asynctaskloader.java:83/))
	at androidx.loader.content.ModernAsyncTask.finish([ModernAsyncTask.java:490](http://modernasynctask.java:490/))
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage([ModernAsyncTask.java:507](http://modernasynctask.java:507/))
	at android.os.Handler.dispatchMessage([Handler.java:106](http://handler.java:106/))
	at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/))
	at android.os.Looper.loop([Looper.java:288](http://looper.java:288/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7891](http://activitythread.java:7891/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:548](http://runtimeinit.java:548/))
	at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:49](http://execinit.java:49/))
	at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:355](http://runtimeinit.java:355/))

-------------------
Version : 0.18.10
Version Code: 291
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Pixel 7
Android Version : 13
User : grapheneos
Total Internal memory : 118015217664
Available Internal memory : 59193143296
-------------------

**Comment by yanus171** [comment]
Install the latest beta 
https://github.com/yanus171/Handy-News-Reader/issues/683
