### ISSUE TITLE
Fediverse RSS links do not work

### ISSUE THREAD

**Issue by advait404** [yanus171/Handy-News-Reader#866]
**Describe the bug**
The RSS links of people's profile should allow us to see their public posts. But HR only shows a blank feed.

**To Reproduce**
1. Go to any fediverse account, like
 https://social.growyourown.services/@FediFollows

2. Add .rss at the end to make it a RSS feed 

https://social.growyourown.services/@FediFollows.rss

3. Add this feed to HR
4. old posts don't show up. Modifying the fetch time to 3 months also does not show old posts
5. New posts don't show op when the account makes a public posts.

**Expected behavior**
The old and new posts should be fetched by HR. 
Tested this with miniflux RSS reader, and it works.

**Smartphone (please complete the following information):**
 - Device: oppo a93
 - OS: android 12
 - Browser: using the HR app, and have stock browser installed

**Comment by dhebbeker** [comment]
I can report that this is also an issue with the related project [spaRSS](https://github.com/Etuldan/spaRSS/). But it works with the Android app [Feeder](https://gitlab.com/spacecowboy/Feeder).

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1704321667

**Comment by advait404** [comment]
Hi, I tried the beta version, but got the below error. This happened after I used and imported the fediverse rss feeds in handy. At first it was able to successfully import the feed and its items, but now I cannot open the app as it crashes as soon as launch it. 


UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.UpdateActions(EntriesListFragment.java:356)
	at ru.yanus171.feedexfork.fragment.EntriesListFragment.onCreateOptionsMenu(EntriesListFragment.java:723)
	at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:3100)
	at androidx.fragment.app.FragmentManager.dispatchCreateOptionsMenu(FragmentManager.java:3181)
	at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:391)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:288)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1218)
	at android.view.Choreographer.doCallbacks(Choreographer.java:972)
	at android.view.Choreographer.doFrame(Choreographer.java:867)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1203)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

-------------------
Version : 0.18.28
Version Code: 310
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: CPH2121
Android Version : 12
Board : k79v1_64
Brand : OPPO
Device : OP4C51L1
Model : CPH2121
Product : CPH2121T2
User : root
Total Internal memory : 114428682240
Available Internal memory : 30069633024
-------------------

**Comment by yanus171** [comment]
Try https://github.com/yanus171/Handy-News-Reader/issues/683#issuecomment-1732390586

**Comment by advait404** [comment]
@yanus171 the beta version  is working without issues.
