### ISSUE TITLE
Uncaught exception - continually

### ISSUE THREAD

**Issue by DickinsonSa** [yanus171/Handy-News-Reader#875]
**Describe the bug**
This only started happening today, nothing that I know of has changed to cause it. Hopefully the log may be of help. 
Ok, sorry for the bad example, I copied it out of Joplin from the link after the crash. Not sure why I've got all the funny symbols. 

Regards 

UNCAUGHT EXCEPTION

Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask���������������.����(���������.����:429)������.����.����������.����������.�����ℎ����������(����������.����:383)������.����.����������.����������.������������(����������.����:252)������.����.����������.����������.���(����������.����:271)���������.��.���������AsyncFutureTask.done(AsyncTask.java:429)atjava.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)atjava.util.concurrent.FutureTask.setException(FutureTask.java:252)atjava.util.concurrent.FutureTask.run(FutureTask.java:271)atandroid.os.AsyncTaskSerialExecutor1.���(���������.����:292)������.����.����������.�ℎ����������������.���������(�ℎ����������������.����:1167)������.����.����������.�ℎ����������������1.run(AsyncTask.java:292)atjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)atjava.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:443)
at android.content.ContentProvider.query(ContentProvider.java:1218)
at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:108)
at android.content.ContentProvider.query(ContentProvider.java:1311)
at android.content.ContentProvider$Transport.query(ContentProvider.java:271)
at android.content.ContentResolver.query(ContentResolver.java:955)
at android.content.ContentResolver.query(ContentResolver.java:891)
at android.content.ContentResolver.query(ContentResolver.java:840)
at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1117)
at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1075)
at android.os.AsyncTask$3.call(AsyncTask.java:389)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: EML-L09
Android Version : 10
User : test
Total Internal memory : 119661395968
Available Internal memory : 98886295552

**Comment by yanus171** [comment]
You have very old app version. Update it from GitHub release section

**Comment by DickinsonSa** [comment]
> You have very old app version. Update it from GitHub release section

Thank you. I will do that.
