### ISSUE TITLE
Instant Crash after Updating

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#888]
**Describe the bug**
Tried upgrading from  v0.18.2 to the newest beta of  0.18.22, it installed properly but when I try to open the app it instantly crashes. Here is the error log

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{eafdc35 u0 ru.yanus171.feedexfork/.service.ReadingService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2075)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

-------------------
Version : 0.18.22
Version Code: 304
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Mi 9T Pro
Android Version : 11
Board : raphael
Brand : Xiaomi
Device : raphael
Model : Mi 9T Pro
Product : raphael
User : builder
Total Internal memory : 117402300416
Available Internal memory : 14424477696
-------------------

**To Reproduce**
1. Upgrade from   v0.18.2

**Expected behavior**
Correctly open the app and load the articles without crashing.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mi 9T Pro
 - OS: Android Version 11
 - Browser [e.g. stock browser, safari] Stock
 - Version [e.g. 22] 0.18.22

**Comment by ArtexJay** [comment]
Update, not sure what changed with the app but after it crashed, i noticed a notification about deleting old articles and the app launches without issue now.

You can reopen if anyone else gets this same issue.
