### ISSUE TITLE
Consistent crash on launch

### ISSUE THREAD

**Issue by omgitsraven** [yanus171/Handy-News-Reader#889]
**Describe the bug**
When I first installed Handy News Reader, it worked fine; but at one point, when switching back to the app, all of my open apps crashed, and now, even after rebooting, I get this error every time I try to launch Handy News Reader:

```
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$4.done(AsyncTask.java:415)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
 at java.util.concurrent.FutureTask.run(FutureTask.java:269)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
 at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:443)
 at android.content.ContentProvider.query(ContentProvider.java:1526)
 at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:108)
 at android.content.ContentProvider.query(ContentProvider.java:1622)
 at android.content.ContentProvider$Transport.query(ContentProvider.java:290)
 at android.content.ContentResolver.query(ContentResolver.java:1226)
 at android.content.ContentResolver.query(ContentResolver.java:1158)
 at android.content.ContentResolver.query(ContentResolver.java:1114)
 at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1117)
 at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1075)
 at android.os.AsyncTask$3.call(AsyncTask.java:394)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 ... 4 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: SM-T970
Android Version : 13
User : dpi
Total Internal memory : 115024556032
Available Internal memory : 84228886528
-------------------
```

**To Reproduce**
1. Tap the "Handy News Reader" icon.

**Expected behavior**
I expected the app to open.

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab S7+
 - OS: Android 13, One UI 5.1

**Additional context**
I imported my feeds from Flym via the OPML export.

**Comment by yanus171** [comment]
Try long tap on the app icon and select Starred articles

**Comment by omgitsraven** [comment]
Whoa, that worked!   And now I can launch it normally.   I guess that works as a workaround for now, but should I leave the issue open until it can be fixed without needing to know this workaround?

**Comment by ArtexJay** [comment]
Encountered a similar issue to this the with consistent crashes, the recommended solution fixed/helped for me. Thanks!

**Comment by omgitsraven** [comment]
OK, I thought this was a permanent fix, but the problem keeps coming back, and each time I have to do the 'starred articles' trick.   So this is an okay workaround, but it's still annoying and a proper fix would be nice.

**Comment by yanus171** [comment]
What do you do to get crash back?

**Comment by omgitsraven** [comment]
It seems to occur every time I open an article in my browser.

The process is this:
- tap icon for Handy, it works
- return to home screen, tap icon again, it works
- in handy, tap an article to view it in handy
- tap the article's name to open it in my browser
- from browser, return to home screen, tap handy icon again
- handy immediately crashes, gives the message.
- tap handy icon again, it immediately crashes.
- press&hold and select "starred articles", handy opens correctly, everything seems fine.
- return to home screen and open again, still fine.
- open article in browser; return to home screen; tap handy icon; crashing again.    hold for "starred articles", fine again.

**Comment by yanus171** [comment]
You have VERY old all version. Update it

**Comment by omgitsraven** [comment]
This is the latest version on the Play Store, by following the link on the readme of this github page!   It says it was last updated Oct 28, 2022?

**Comment by yanus171** [comment]
See #873

**Comment by yanus171** [comment]
Hey the latest app version from https://github.com/yanus171/Handy-News-Reader/releases or #683

**Comment by omgitsraven** [comment]
Hah, yes -- that fixes my crash, thank you :)

I do recommend you take the Play Store link out of the readme if it isn't meant to be used!
