### ISSUE TITLE
Crash on Launch After Update to 0.18.25

### ISSUE THREAD

**Issue by ArtexJay** [yanus171/Handy-News-Reader#894]
**Describe the bug**
Constant crashing after updating to 0.18.25 from 0.18.22

**Expected behavior**
Shouldn't crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9T Pro
 - OS: Android 11
 - Browser Stock
 - APP version 0.18.25

**Additional context**
UNCAUGHT EXCEPTION
-------------------
Stacktrace:
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cbe42b6 u0 ru.yanus171.feedexfork/.service.ReadingService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2075)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

-------------------
Version : 0.18.25
Version Code: 307
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: Mi 9T Pro
Android Version : 11
Board : raphael
Brand : Xiaomi
Device : raphael
Model : Mi 9T Pro
Product : raphael
User : builder
Total Internal memory : 117402300416
Available Internal memory : 2410786816
-------------------

**Comment by ArtexJay** [comment]
After many relaunching it worked. So I'll close.
