### ISSUE TITLE
Uncaught exception at startup

### ISSUE THREAD

**Issue by ozbrewer** [yanus171/Handy-News-Reader#898]
Startup fails with uncaught exception:

UNCAUGHT EXCEPTION
-------------------
Stacktrace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:415)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Illegal query. Match code=-1; uri=content://ru.yanus171.feedexfork.provider.FeedData/entries/-1
at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:443)
at android.content.ContentProvider.query(ContentProvider.java:1385)
at ru.yanus171.feedexfork.provider.FeedDataContentProvider.query(FeedDataContentProvider.java:108)
at android.content.ContentProvider.query(ContentProvider.java:1481)
at android.content.ContentProvider$Transport.query(ContentProvider.java:279)
at android.content.ContentResolver.query(ContentResolver.java:1187)
at android.content.ContentResolver.query(ContentResolver.java:1118)
at android.content.ContentResolver.query(ContentResolver.java:1074)
at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1117)
at ru.yanus171.feedexfork.fragment.EntryFragment$8.doInBackground(EntryFragment.java:1075)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

-------------------
Version : 0.17.22
Version Code: 280
Package : ru.yanus171.feedexfork
FilePath : /data/user/0/ru.yanus171.feedexfork/files
Phone Model: TabUltraC
Android Version : 11
User : root
Total Internal memory : 118795071488
Available Internal memory : 86689136640
-------------------

**Comment by yanus171** [comment]
Install the latest app version from 
https://github.com/yanus171/Handy-News-Reader/releases/latest 
https://github.com/yanus171/Handy-News-Reader/issues/683

**Comment by ozbrewer** [comment]
Thanks - updated to the apk. Seems ok.
